#!/usr/bin/env python3
"""Generate a simple badge gallery HTML page."""

import os
from datetime import datetime, timezone

BADGES = [
    ("Build Status", "build-passing-brightgreen"),
    ("Coverage", "coverage-87%25-yellow"),
    ("Python", "python-3.11%20%7C%203.12-blue"),
    ("License", "license-MIT-green"),
]


def generate_badge_url(label: str, message: str) -> str:
    """Generate shields.io badge URL."""
    return f"https://img.shields.io/badge/{message}"


def generate_html() -> str:
    """Generate the gallery HTML."""
    badge_items = []
    for name, badge_path in BADGES:
        url = generate_badge_url(name, badge_path)
        badge_items.append(f'<div class="badge-item">')
        badge_items.append(f'  <h3>{name}</h3>')
        badge_items.append(f'  <img src="{url}" alt="{name}">')
        badge_items.append(f'</div>')

    badges_html = "\n    ".join(badge_items)
    build_time = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    commit_sha = os.environ.get("GITHUB_SHA", "local")[:7]

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Badge Gallery - badge-gen</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 2rem;
            background: #f6f8fa;
        }}
        h1 {{ color: #24292f; }}
        .badge-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
            gap: 1rem;
            margin-top: 2rem;
        }}
        .badge-item {{
            background: white;
            padding: 1rem;
            border-radius: 6px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }}
        .badge-item h3 {{
            margin: 0 0 0.5rem 0;
            font-size: 0.9rem;
            color: #57606a;
        }}
        .footer {{
            margin-top: 2rem;
            padding-top: 1rem;
            border-top: 1px solid #d0d7de;
            font-size: 0.8rem;
            color: #57606a;
        }}
    </style>
</head>
<body>
    <h1>🏷️ Badge Gallery</h1>
    <p>Example badges generated by badge-gen</p>

    <div class="badge-grid">
    {badges_html}
    </div>

    <div class="footer">
        <p>Built at {build_time} | Commit: {commit_sha}</p>
    </div>
</body>
</html>"""


if __name__ == "__main__":
    print(generate_html())
